import {
  AttachmentBuilder,
  Client,
  DiscordAPIError,
  EmbedBuilder,
  Events,
  GatewayIntentBits,
  Message,
  Partials,
} from 'discord.js';
import {
  CreateImage,
  CreateImageResponseFormat,
  CreateImageSize,
} from '../src/lib/OpenAI';
import {
  LogLevel,
  Logger,
} from '../src/lib/Logger';
import { Config } from '../src/lib/Config';

const config = new Config();
const discordClient = new Client({
  intents: [
    GatewayIntentBits.DirectMessages,
    GatewayIntentBits.Guilds,
    GatewayIntentBits.GuildMessages,
    GatewayIntentBits.MessageContent,
  ],
  partials: [ Partials.Channel ],
});
discordClient.login(String(config.Settings.DISCORD_BOT_TOKEN));

discordClient.once(Events.ClientReady, async client => {
  Logger.log({
    message: `Discord client is connected as ${client.user.tag}.`,
    logLevel: LogLevel.Info,
  });
});

discordClient.on(Events.MessageCreate, async message => {
  await _embedImageFromPromptMessage(message);
});

/**
 * Test function to send an image from a prompt received in a Discord message
 * @param discordMessage Discord message passed by the Events.MessageCreate event
 */
async function _embedImageFromPromptMessage(discordMessage: Message): Promise<void> {
  const promptTag = '{test-image}';
  const messageIsImagePrompt = discordMessage.content.includes(promptTag);

  if (messageIsImagePrompt) {
    const imagePrompt = discordMessage.content.replace(promptTag, '');

    const openAiClient = new CreateImage({
      apiKey: String(config.Settings.OPENAI_API_KEY),
      maxRetries: Number(config.Settings.OPENAI_MAX_RETRIES),
    });

    const response = await openAiClient.createImage({
      numberOfImages: 1,
      prompt: imagePrompt,
      responseFormat: CreateImageResponseFormat.B64Json,
      size: CreateImageSize.Medium,
      user: discordMessage.author.username,
    });

    const embed = new EmbedBuilder()
      .setTitle('ai maed dis')
      .setDescription(imagePrompt)
      .addFields(
        { name: 'Generated by:', value: String(discordMessage.author.tag), inline: true },
        { name: 'Tokens remaining:', value: String(5), inline: true }
      )
      .setImage(('url' in response.data[0]) ?
        response.data[0].url :
        `attachment://${new AttachmentBuilder(response.data[0].b64_json, { name: `openai-image-${Date.now()}.png` }).name}`)
      .setFooter({
        text: 'jlyons210/discord-bot-ol-bootsie',
        iconURL: 'https://grumple.cloud/assets/discord-bot-ol-bootsie/icon-github.png',
      })
      .setTimestamp();

    const files: AttachmentBuilder[] = [];
    if ('url' in response.data[0]) {
      embed.setImage(response.data[0].url);
    }
    else if ('b64_json' in response.data[0]) {
      files.push(new AttachmentBuilder(
        Buffer.from(response.data[0].b64_json, 'base64'),
        { name: `openai-image-${Date.now()}.png` }
      ));
      embed.setImage(`attachment://${files[0].name}`);
    }

    try {
      discordMessage.channel.send({ embeds: [embed], files: files });
    }
    catch (e) {
      if (e instanceof DiscordAPIError) {
        Logger.log({
          message: e.message,
          logLevel: LogLevel.Error,
        });
      }
    }
  }
}